version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ai-teacher-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: aiuser
      POSTGRES_PASSWORD: aipassword123
      POSTGRES_DB: ai_teacher_training
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aiuser -d ai_teacher_training"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-teacher-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://aiuser:aipassword123@postgres:5432/ai_teacher_training?schema=public"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "your-super-secret-key-change-in-production"
    ports:
      - "3000:3000"
    command: >
      sh -c "npx prisma migrate deploy && node server.js"

volumes:
  postgres_data:
